<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Security hardening: file editor, XML-RPC, headers, PHP uploads, REST API, version hiding.
 */
class WPFG_Hardening {

    /**
     * Initialize hardening hooks on every request.
     */
    public static function init() {
        // File editor disable via mu-plugin.
        if ( WPFG_Settings::get( 'hardening_disable_file_editor', false ) ) {
            self::apply_file_editor_disable();
        } else {
            self::remove_file_editor_disable();
        }

        // Disable XML-RPC.
        if ( WPFG_Settings::get( 'hardening_disable_xmlrpc', false ) ) {
            add_filter( 'xmlrpc_enabled', '__return_false' );
            add_filter( 'wp_headers', array( __CLASS__, 'remove_pingback_header' ) );
        }

        // Security headers.
        if ( WPFG_Settings::get( 'hardening_security_headers', false ) ) {
            add_action( 'send_headers', array( __CLASS__, 'send_security_headers' ) );
        }

        // Block PHP in uploads.
        if ( WPFG_Settings::get( 'hardening_block_php_uploads', false ) ) {
            self::apply_block_php_uploads();
        } else {
            self::remove_block_php_uploads();
        }

        // Disable REST API for unauthenticated users.
        if ( WPFG_Settings::get( 'hardening_disable_rest_unauth', false ) ) {
            add_filter( 'rest_authentication_errors', array( __CLASS__, 'restrict_rest_api' ) );
        }

        // Hide WordPress version.
        if ( WPFG_Settings::get( 'hardening_hide_wp_version', false ) ) {
            remove_action( 'wp_head', 'wp_generator' );
            add_filter( 'the_generator', '__return_empty_string' );
            add_filter( 'style_loader_src', array( __CLASS__, 'remove_version_query' ), 10, 2 );
            add_filter( 'script_loader_src', array( __CLASS__, 'remove_version_query' ), 10, 2 );
        }
    }

    // ------------------------------------------------------------------
    // File Editor Disable
    // ------------------------------------------------------------------

    /**
     * Create mu-plugin that defines DISALLOW_FILE_EDIT.
     */
    private static function apply_file_editor_disable() {
        $mu_dir  = ABSPATH . 'wp-content/mu-plugins';
        $mu_file = $mu_dir . '/wpfg-file-editor-disable.php';

        if ( file_exists( $mu_file ) ) {
            return;
        }

        if ( ! is_dir( $mu_dir ) ) {
            wp_mkdir_p( $mu_dir );
        }

        $content = "<?php\n// Auto-generated by WP File Guardian – do not edit.\nif ( ! defined( 'DISALLOW_FILE_EDIT' ) ) {\n    define( 'DISALLOW_FILE_EDIT', true );\n}\n";

        if ( @file_put_contents( $mu_file, $content ) !== false ) {
            WPFG_Logger::log( 'hardening', 'file_editor', 'disabled', 'Created mu-plugin to disable file editor' );
        }
    }

    /**
     * Remove the mu-plugin when the setting is off.
     */
    private static function remove_file_editor_disable() {
        $mu_file = ABSPATH . 'wp-content/mu-plugins/wpfg-file-editor-disable.php';

        if ( file_exists( $mu_file ) ) {
            @unlink( $mu_file );
            WPFG_Logger::log( 'hardening', 'file_editor', 'enabled', 'Removed mu-plugin; file editor re-enabled' );
        }
    }

    // ------------------------------------------------------------------
    // XML-RPC
    // ------------------------------------------------------------------

    /**
     * Remove X-Pingback header.
     *
     * @param  array $headers
     * @return array
     */
    public static function remove_pingback_header( $headers ) {
        unset( $headers['X-Pingback'] );
        return $headers;
    }

    // ------------------------------------------------------------------
    // Security Headers
    // ------------------------------------------------------------------

    /**
     * Send security headers.
     */
    public static function send_security_headers() {
        if ( headers_sent() ) {
            return;
        }

        $x_frame  = WPFG_Settings::get( 'hardening_x_frame_options', 'SAMEORIGIN' );
        $referrer  = WPFG_Settings::get( 'hardening_referrer_policy', 'strict-origin-when-cross-origin' );

        header( 'X-Frame-Options: ' . $x_frame );
        header( 'X-Content-Type-Options: nosniff' );
        header( 'X-XSS-Protection: 1; mode=block' );
        header( 'Referrer-Policy: ' . $referrer );
        header( 'Permissions-Policy: camera=(), microphone=(), geolocation=()' );
    }

    // ------------------------------------------------------------------
    // Block PHP in Uploads
    // ------------------------------------------------------------------

    /**
     * Write .htaccess rule to block PHP execution in uploads.
     */
    private static function apply_block_php_uploads() {
        $upload_dir = wp_upload_dir();
        $htaccess   = trailingslashit( $upload_dir['basedir'] ) . '.htaccess';

        $marker_start = '# BEGIN WP File Guardian';
        $marker_end   = '# END WP File Guardian';
        $rules        = "<Files *.php>\nDeny from all\n</Files>";
        $block        = $marker_start . "\n" . $rules . "\n" . $marker_end;

        // If file exists, check whether our block is already present.
        if ( file_exists( $htaccess ) ) {
            $contents = file_get_contents( $htaccess );
            if ( strpos( $contents, $marker_start ) !== false ) {
                return; // Already applied.
            }
            $block = $block . "\n" . $contents;
        }

        if ( @file_put_contents( $htaccess, $block ) !== false ) {
            WPFG_Logger::log( 'hardening', 'php_uploads', 'blocked', 'Added .htaccess rule to block PHP in uploads' );
        }
    }

    /**
     * Remove our .htaccess rules from uploads directory.
     */
    private static function remove_block_php_uploads() {
        $upload_dir = wp_upload_dir();
        $htaccess   = trailingslashit( $upload_dir['basedir'] ) . '.htaccess';

        if ( ! file_exists( $htaccess ) ) {
            return;
        }

        $contents     = file_get_contents( $htaccess );
        $marker_start = '# BEGIN WP File Guardian';
        $marker_end   = '# END WP File Guardian';

        $pattern = '/' . preg_quote( $marker_start, '/' ) . '.*?' . preg_quote( $marker_end, '/' ) . '\n?/s';
        $updated = preg_replace( $pattern, '', $contents );

        if ( $updated !== $contents ) {
            $updated = trim( $updated );
            if ( empty( $updated ) ) {
                @unlink( $htaccess );
            } else {
                @file_put_contents( $htaccess, $updated );
            }
            WPFG_Logger::log( 'hardening', 'php_uploads', 'unblocked', 'Removed .htaccess rule from uploads' );
        }
    }

    // ------------------------------------------------------------------
    // REST API Restriction
    // ------------------------------------------------------------------

    /**
     * Block REST API for unauthenticated users.
     *
     * @param  WP_Error|null|true $result
     * @return WP_Error|null|true
     */
    public static function restrict_rest_api( $result ) {
        if ( ! empty( $result ) ) {
            return $result;
        }

        if ( ! is_user_logged_in() ) {
            return new WP_Error(
                'rest_not_logged_in',
                __( 'REST API access restricted to authenticated users.', 'wp-file-guardian' ),
                array( 'status' => 401 )
            );
        }

        return $result;
    }

    // ------------------------------------------------------------------
    // Hide WP Version
    // ------------------------------------------------------------------

    /**
     * Remove ?ver= query string from enqueued styles and scripts.
     *
     * @param  string $src
     * @param  string $handle
     * @return string
     */
    public static function remove_version_query( $src, $handle = '' ) {
        if ( strpos( $src, 'ver=' ) !== false ) {
            $src = remove_query_arg( 'ver', $src );
        }
        return $src;
    }

    // ------------------------------------------------------------------
    // Status Helpers
    // ------------------------------------------------------------------

    /**
     * Return an array describing the current status of every hardening item.
     *
     * @return array
     */
    public static function get_status() {
        $items = self::get_hardening_items();
        $status = array();

        foreach ( $items as $key => $item ) {
            $enabled = (bool) WPFG_Settings::get( $key, false );
            $status[ $key ] = array(
                'key'         => $key,
                'title'       => $item['title'],
                'description' => $item['description'],
                'enabled'     => $enabled,
            );
        }

        return $status;
    }

    /**
     * Apply all hardening measures based on current settings.
     */
    public static function apply_all() {
        // File editor.
        if ( WPFG_Settings::get( 'hardening_disable_file_editor', false ) ) {
            self::apply_file_editor_disable();
        } else {
            self::remove_file_editor_disable();
        }

        // PHP uploads.
        if ( WPFG_Settings::get( 'hardening_block_php_uploads', false ) ) {
            self::apply_block_php_uploads();
        } else {
            self::remove_block_php_uploads();
        }

        WPFG_Logger::log( 'hardening', 'apply_all', 'success', 'All hardening measures re-applied based on current settings' );
    }

    /**
     * Test what is actually active on the server vs what the settings say.
     *
     * @return array
     */
    public static function test_status() {
        $results = array();

        // File editor.
        $results['hardening_disable_file_editor'] = array(
            'setting' => (bool) WPFG_Settings::get( 'hardening_disable_file_editor', false ),
            'actual'  => defined( 'DISALLOW_FILE_EDIT' ) && DISALLOW_FILE_EDIT,
            'match'   => ( (bool) WPFG_Settings::get( 'hardening_disable_file_editor', false ) ) === ( defined( 'DISALLOW_FILE_EDIT' ) && DISALLOW_FILE_EDIT ),
        );

        // XML-RPC: check if filter returns false.
        $xmlrpc_setting = (bool) WPFG_Settings::get( 'hardening_disable_xmlrpc', false );
        $xmlrpc_actual  = ! apply_filters( 'xmlrpc_enabled', true );
        $results['hardening_disable_xmlrpc'] = array(
            'setting' => $xmlrpc_setting,
            'actual'  => $xmlrpc_actual,
            'match'   => $xmlrpc_setting === $xmlrpc_actual,
        );

        // Security headers: cannot fully test without an HTTP request; check setting only.
        $results['hardening_security_headers'] = array(
            'setting' => (bool) WPFG_Settings::get( 'hardening_security_headers', false ),
            'actual'  => (bool) WPFG_Settings::get( 'hardening_security_headers', false ),
            'match'   => true,
        );

        // PHP uploads: check .htaccess.
        $upload_dir       = wp_upload_dir();
        $htaccess         = trailingslashit( $upload_dir['basedir'] ) . '.htaccess';
        $php_block_exists = false;
        if ( file_exists( $htaccess ) ) {
            $content = file_get_contents( $htaccess );
            $php_block_exists = strpos( $content, '# BEGIN WP File Guardian' ) !== false;
        }
        $results['hardening_block_php_uploads'] = array(
            'setting' => (bool) WPFG_Settings::get( 'hardening_block_php_uploads', false ),
            'actual'  => $php_block_exists,
            'match'   => ( (bool) WPFG_Settings::get( 'hardening_block_php_uploads', false ) ) === $php_block_exists,
        );

        // REST API: check if filter is hooked.
        $rest_setting = (bool) WPFG_Settings::get( 'hardening_disable_rest_unauth', false );
        $rest_actual  = has_filter( 'rest_authentication_errors', array( __CLASS__, 'restrict_rest_api' ) ) !== false;
        $results['hardening_disable_rest_unauth'] = array(
            'setting' => $rest_setting,
            'actual'  => $rest_actual,
            'match'   => $rest_setting === $rest_actual,
        );

        // Hide WP version: check if generator action is removed.
        $version_setting = (bool) WPFG_Settings::get( 'hardening_hide_wp_version', false );
        $version_actual  = has_filter( 'the_generator', '__return_empty_string' ) !== false;
        $results['hardening_hide_wp_version'] = array(
            'setting' => $version_setting,
            'actual'  => $version_actual,
            'match'   => $version_setting === $version_actual,
        );

        return $results;
    }

    // ------------------------------------------------------------------
    // Internal
    // ------------------------------------------------------------------

    /**
     * Hardening items definition.
     *
     * @return array
     */
    private static function get_hardening_items() {
        return array(
            'hardening_disable_file_editor' => array(
                'title'       => __( 'Disable File Editor', 'wp-file-guardian' ),
                'description' => __( 'Disables the built-in WordPress theme and plugin file editor to prevent code changes from the admin area.', 'wp-file-guardian' ),
            ),
            'hardening_disable_xmlrpc' => array(
                'title'       => __( 'Disable XML-RPC', 'wp-file-guardian' ),
                'description' => __( 'Disables XML-RPC and removes the X-Pingback header. Prevents brute-force and DDoS attacks via XML-RPC.', 'wp-file-guardian' ),
            ),
            'hardening_security_headers' => array(
                'title'       => __( 'Security Headers', 'wp-file-guardian' ),
                'description' => __( 'Adds X-Frame-Options, X-Content-Type-Options, X-XSS-Protection, Referrer-Policy, and Permissions-Policy headers.', 'wp-file-guardian' ),
            ),
            'hardening_block_php_uploads' => array(
                'title'       => __( 'Block PHP in Uploads', 'wp-file-guardian' ),
                'description' => __( 'Adds an .htaccess rule to prevent PHP execution inside the uploads directory.', 'wp-file-guardian' ),
            ),
            'hardening_disable_rest_unauth' => array(
                'title'       => __( 'Restrict REST API', 'wp-file-guardian' ),
                'description' => __( 'Blocks REST API access for unauthenticated visitors. Logged-in users are unaffected.', 'wp-file-guardian' ),
            ),
            'hardening_hide_wp_version' => array(
                'title'       => __( 'Hide WordPress Version', 'wp-file-guardian' ),
                'description' => __( 'Removes the WordPress version from the page source, RSS feeds, and enqueued asset URLs.', 'wp-file-guardian' ),
            ),
        );
    }
}
